#!/bin/bash

# Run the container with 
docker run -it \
    --name base_python_container \
    -v ./:/app \
    base_python bash

# Open a shell prompt inside the container
docker exec -it base_python_container bash